baseURL = "https://helpgroup.netlify.app/"
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
title = "HELP Group"
enableRobotsTXT = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"

# ========== LANGUAGES ==========
[languages]

  [languages.vi]
    languageCode = "vi"
    languageName = "Tiếng Việt"
    title = "HELP Group"
    weight = 1
    [languages.vi.params]
      description = "Nhóm Nghiên cứu kết nối bằng chứng và chính sách y tế (HELP Group)"
    [[languages.vi.menus.main]]
      name = "Lĩnh vực nghiên cứu"
      url = "/#research"
      weight = 1
    [[languages.vi.menus.main]]
      name = "Thành viên"
      url = "/members/"
      weight = 2
    [[languages.vi.menus.main]]
      name = "Bài báo"
      url = "/#publications"
      weight = 3
    [[languages.vi.menus.main]]
      name = "Dự án"
      url = "/#projects"
      weight = 4
    [[languages.vi.menus.main]]
      name = "Tin tức"
      url = "/#news"
      weight = 5
    [[languages.vi.menus.main]]
      name = "Liên hệ"
      url = "/#contact"
      weight = 6

  [languages.en]
    languageCode = "en"
    languageName = "English"
    title = "HELP Group"
    weight = 2
    [languages.en.params]
      description = "Health Evidence Linkage to Policy Research Group (HELP Group)"
    [[languages.en.menus.main]]
      name = "Research"
      url = "/en/#research"
      weight = 1
    [[languages.en.menus.main]]
      name = "Members"
      url = "/en/members/"
      weight = 2
    [[languages.en.menus.main]]
      name = "Publications"
      url = "/en/#publications"
      weight = 3
    [[languages.en.menus.main]]
      name = "Projects"
      url = "/en/#projects"
      weight = 4
    [[languages.en.menus.main]]
      name = "News"
      url = "/en/#news"
      weight = 5
    [[languages.en.menus.main]]
      name = "Contact"
      url = "/en/#contact"
      weight = 6
